version: '3'

services:
  flask_alpine:
    image: "new_flaskapp"
    ports:
      - "5000:5000"
    volumes:
      - "./:/app"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    networks:
      nova_rede:
        ipv4_address: 200.100.50.5

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - "db:/data/db"
    networks:
      nova_rede:
        ipv4_address: 200.100.50.50

  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     nova_rede:
  #       ipv4_address: 200.100.50.51

networks:
  nova_rede:
    driver: bridge
    ipam:
      config:
        - subnet: 200.100.50.0/24

volumes:
  db: